### ISSUE TITLE
source does not compile jade when the file contain "include" and "extend"

### ISSUE THREAD

**Issue by glivera** [sourcejs/sourcejs.com#2]
### index.jade

``` jade
include ../../jade/test

h1 Button Spec
.source_info
    p Basic button spec demo
section.source_section
    h2 Basic button
    .source_example
        a.btn.btn-primary(href="#777") Button
```
### error

Error: No default engine was specified and no extension was pro
vided.
    at new View (D:\work_projects\source_test\www\node_modules\express\lib\view.js:41:42)
    at Function.app.render (D:\work_projects\source_test\www\node_modules\express\lib\application.js:49
9:12)
    at ServerResponse.res.render (D:\work_projects\source_test\www\node_modules\express\lib\response.js
:955:7)
    at errorHandler (D:\work_projects\source_test\www\app.js:197:9)
    at Layer.handle_error (D:\work_projects\source_test\www\node_modules\express\lib\router\layer.js:52
:5)
    at trim_prefix (D:\work_projects\source_test\www\node_modules\express\lib\router\index.js:261:13)
    at D:\work_projects\source_test\www\node_modules\express\lib\router\index.js:230:9
    at Function.proto.process_params (D:\work_projects\source_test\www\node_modules\express\lib\router\
index.js:305:12)
    at D:\work_projects\source_test\www\node_modules\express\lib\router\index.js:221:12
    at Function.match_layer (D:\work_projects\source_test\www\node_modules\express\lib\router\index.js:
288:3)

**Comment by robhrt7** [comment]
Thanks for the report, we will test it. But note that this is related to separate SourceJS plugin https://github.com/sourcejs/sourcejs-jade. By the way, did you installed it?

**Comment by robhrt7** [comment]
I duplicated task in corresponding repo https://github.com/sourcejs/sourcejs-jade/issues/1

**Comment by glivera** [comment]
Yes i do.
These errors are output when using this plugin.

**Comment by robhrt7** [comment]
Issue fixed in corresponding plugin.
